### ISSUE TITLE
Should we translate source code outputs and comments?

### ISSUE THREAD

**Issue by simsim0709** [reactjs/ko.reactjs.org#10]
<img width="779" alt="screen shot 2019-02-10 at 12 07 15 am" src="https://user-images.githubusercontent.com/10040154/52522387-19d54780-2cc8-11e9-8dc4-03fe17754429.png">

Regarding the scope of translation, we need to discuss what to translate and what not to translate.

Any suggestion?

**Comment by ENvironmentSet** [comment]
I don't have any strong opinion about translating string values. But in my opinion, we must translate source code comments since they are highly associated with contents of documents.

**Comment by cadenzah** [comment]
In my case, I translate only comments, nothing else.

**Comment by hg-pyun** [comment]
I think it would be a good idea to translate the comment.

**Comment by taehwanno** [comment]
This will be fixed in #14
