### ISSUE TITLE
Add DocSearch suppport

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ko.reactjs.org#104]
Hi there!

Congrats on almost finishing the Korean translation of the React docs. Before releasing, we have one more task to do. We need to change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25) . One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program) in order to do this.

**Comment by taehwanno** [comment]
Thanks. I signed up. I will change the DocSearch API Key.

**Comment by hg-pyun** [comment]
I'll delegate it to @taehwano. Thank you.
