### ISSUE TITLE
typo in 'React 최상위 API' page

### ISSUE THREAD

**Issue by hapumee** [reactjs/ko.reactjs.org#115]
I'm so sorry, but there might be a typo on the page below.
(on Chrome, It doesn't show up on IE.)
https://ko.reactjs.org/docs/react-api.html
I think that 'ㄴㄴ' should be removed.

>개요 > 컴포넌트 > React 컴포넌트를 사용하면 UI를 독립적이고 재사용할 수 있는 부분으로 나누고 각 부분을 분리하여 "생각할 수" 있습니다.

**Comment by simsim0709** [comment]
Thanks @hapumee 👍
