### ISSUE TITLE
typo in 'create a new react app' page

### ISSUE THREAD

**Issue by hapumee** [reactjs/ko.reactjs.org#146]
I'm so sorry to mention about this, but the page 'create-a-new-react-app.html' doesn't show up whole contents of it on Chrome and IE also. (Part of the contents show up on the page)
I think that it's because of script tag(<script>) below.

![line_25](https://user-images.githubusercontent.com/1381259/60086697-8718df00-9776-11e9-853b-75be4b93a3a6.png)

It might be translated "<script>" tag instead of  " \`<script>\` " text, so the browser treats it as a HTML tag.

- https://reactjs.org/docs/create-a-new-react-app.html
- https://ko.reactjs.org/docs/create-a-new-react-app.html

- PR https://github.com/reactjs/ko.reactjs.org/pull/64 (line 25)

I think that it's better to modify that. ^^;

**Comment by taehwanno** [comment]
Ahhhhhhhhh... I will fix this. thanks for reporting this 👍
