### ISSUE TITLE
Review remain pull request

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.reactjs.org#161]
The remaining PR reviews are not being reviewed for a long time. Please give us your opinion on what to do from now on.

**Comment by taehwanno** [comment]
Sorry for the late response. 😢 I think my personal work will be done at the end of September. I will be able to participate actively in October.

**Comment by gnujoow** [comment]
As personal schedule is over, I can participate more actively from this month.

**Comment by hg-pyun** [comment]
@taehwanno @gnujoow 
The Pull Request is currently being left unattended. Maintainers are too busy to manage. Why don't you lower the limit with an approve?

**Comment by taehwanno** [comment]
@hg-pyun yes :cry: I agree.

**Comment by taehwanno** [comment]
@reactjs/reactjs-org-korean-translation When I looked at https://github.com/reactjs/reactjs.org/issues/3308, the React docs will be likely to change to hooks-first in 2021 early. Although the scope of the change is uncertain, it seems good that the PRs submitted so far are quickly merged. I wonder if you can help :)

**Comment by taehwanno** [comment]
Every pull request was closed. So I will close this :)
