### ISSUE TITLE
Wrong translation in docs/hooks-state.html

### ISSUE THREAD

**Issue by 1more** [reactjs/ko.reactjs.org#163]
Hi,
I am a beginner of react-hooks and I really appreciates for your translation works.

I found a small mistranslation in https://reactjs.org/docs/hooks-state.html#declaring-a-state-variable page.

- English version
```
What do we pass to useState as an argument? The only argument to the useState() Hook is the initial state. 
Unlike with classes, the state doesn’t have to be an object.
...
```

- Korean version
```
useState의 인자로 무엇을 넘겨주어야 할까요? useState()Hook의 인자로 넘겨주는 값은 state의 초기 값입니다.
함수 컴포넌트의 state는 클래스와 달리 객체를 가질 수 없고, 숫자 타입과 문자 타입을 가질 수 있습니다. 
```

`the state doesn't have to be an object` is translated as `객체를 가질 수 없고` for now,
but `객체일 필요가 없고` could be more correct one for this case.

Thanks.

**Comment by taehwanno** [comment]
Thanks for reporting this. the suggestion is fine but I prefer to `객체일 필요는 없고`.
can you fix this and make some pull request?
