### ISSUE TITLE
typo in 'Hello World' page

### ISSUE THREAD

**Issue by PARK-JONGSEOK** [reactjs/ko.reactjs.org#171]
- 문제 페이지 : https://ko.reactjs.org/docs/hello-world.html
- Explorer에서는 정상적으로 표시되지만, Chrome에서는 이상하게 표시됩니다. :cry: 
- Explorer
  ![image](https://user-images.githubusercontent.com/47925447/65367406-10ec2180-dc6c-11e9-86bb-bb9207dba775.png)
- Chrome
  ![image](https://user-images.githubusercontent.com/47925447/65367408-1a758980-dc6c-11e9-9403-c1215d093a4c.png)

**Comment by taehwanno** [comment]
제보해주셔서 감사합니다. #172 에서 해결되었습니다 :)
