### ISSUE TITLE
PR merge rule and PR template suggestion

### ISSUE THREAD

**Issue by gnujoow** [reactjs/ko.reactjs.org#23]
# pr merge
Since no PR has been merged yet, I think it would be good to make rule for merging PR. 

# pr template

```
<!--

Thank you for the PR! Contributors like you keep React awesome!

Please see the Contribution Guide for guidelines:

https://github.com/reactjs/reactjs.org/blob/master/CONTRIBUTING.md

If your PR references an existing issue, please add the issue number below

-->
```

here is the current PR template, but if the checklist is included here, contributors and reviewers can check the progress of the PR so it can bring better communicate better.

**Comment by gnujoow** [comment]
for PR mege I suggest PR is merged if it has (at least) two approve from reviewer or maintainer to check the quality of the translation.

<img width="753" alt="2019-02-12 10 50 40" src="https://user-images.githubusercontent.com/10865414/52639922-c148b900-2f18-11e9-8c33-076a4a38e640.png">

**Comment by gnujoow** [comment]
```
<!--

Thank you for the PR! Contributors like you keep React awesome!

Please see the Contribution Guide for guidelines:

https://github.com/reactjs/reactjs.org/blob/master/CONTRIBUTING.md

If your PR references an existing issue, please add the issue number below

-->

**progress**  

[ ] 번역 초안 작성
[ ] glossary 용어 확인 (wiki or issue links)
[ ] 띄어쓰기 검사 (http://speller.cs.pusan.ac.kr/)
[ ] 리뷰 반영
[ ] 최종 PR
```

if this checklist included in template, I think this will be able to help contributors to check their tranlation progress.

**Comment by taehwanno** [comment]
> for PR mege I suggest PR is merged if it has (at least) two approve from reviewer or maintainer to check the quality of the translation.

I agree :)

> if this checklist included in template, I think this will be able to help contributors to check their tranlation progress.

Good idea. We need to add `UNIVERSAL-STYLE-GUIDE.md`.

**Comment by hg-pyun** [comment]
Yeah, It is a very coool idea.

**Comment by taggon** [comment]
I think the third item should be "맞춤법 검사" rather than "띄어쓰기 검사", as the online tool checks more than spacing.

**Comment by cadenzah** [comment]
The idea of progress items is pretty nice. It will be easier to check important stuffs.

**Comment by taehwanno** [comment]
I applied "Require pull request reviews before merging" with options in the screenshot.

**Comment by simsim0709** [comment]
I agree 👍

**Comment by gnujoow** [comment]
I will close this issue and make PR for PR templete this sunday. if there is any feed back on the checklist, comment on this thread by this week.

**Comment by taggon** [comment]
The current PR template, which introduced by #25, contains broken links. If we don't have appropriate references for the items yet, it would be better to remove the links.

![image](https://user-images.githubusercontent.com/212034/52912568-ee260480-3267-11e9-857c-b3955bd9d98b.png)

**Comment by gnujoow** [comment]
@taggon I've just made pr to resolve the issue you mention.
https://github.com/reactjs/ko.reactjs.org/pull/45
