### ISSUE TITLE
Draft: Best practices for translation

### ISSUE THREAD

**Issue by taggon** [reactjs/ko.reactjs.org#27]
I wrote a draft of "Best practices for translation" document. Will appreciate any feedback from you. :)
"번역 모범 사례" 문서의 초안을 작성해보았습니다. 보시고 의견있으시면 주세요. 어떤 피드백이든 환영합니다. :)

-----

# 모범사례

## 쌍점은 거의 사용하지 않습니다.

한국어 맞춤법에서는 쌍점(colon, 콜론)을 사용하는 경우를 규정하고 있는데 항목의 열거나 희곡 대사 등에서만 제한적으로 사용합니다([참고](https://www.korean.go.kr/front/page/pageView.do?page_id=P000197&mn_id=30)). 특히 영어처럼 문장 끝에 쌍점을 붙이는 경우는 없으므로 주의하세요.

```
👍모범 사례
다음 예제를 보세요.

👎잘못된 사례
다음 예제를 보세요:
```

## '시'는 제한적으로 사용합니다.

존칭을 표현하는 '-시-'는 문장의 간결함을 해칠 수 있습니다. `~하세요`처럼 제한적인 경우에만 사용하고 그 외에는 사용하지 않는 편이 좋습니다. 다만, 작업자들끼리 대화할 때는 존중의 의미에서 사용해도 상관없습니다.

```
👍모범 사례
살펴보면 좋습니다.

👍모범 사례
살펴보세요.

👎잘못된 사례
살펴보시면 좋습니다.
```

## 쉼표를 모두 옮길 필요는 없습니다.

영어와 우리말에서 쉼표를 사용하는 사례가 다릅니다. 우리말에서 쉼표를 사용하는 몇 가지 경우는 [맞춤법](https://www.korean.go.kr/front/page/pageView.do?page_id=P000195&mn_id=30)에 규정되어 있습니다. 꼭 필요할 때만 사용하고 그 외에는 제한하는 편이 좋을 것 같습니다. 

```
🇬🇧For example, if `id` is the row ID, either of the following would work

👍모범 사례
예를 들어 `id`가 행의 ID일 경우 다음 코드가 모두 작동합니다.

👎잘못된 사례
예를 들어, `id`가 행의 ID일 경우 다음 코드가 모두 작동합니다.
```

## render = 렌더링하다

`render`나 `bind`처럼 우리말 번역이 없고 원문의 음만 따서 쓰는 동사는 명사형 + `~하다`로 번역하는 게 좋습니다.

```
🇬🇧 React renders DOM elements.

👍모범 사례
React는 DOM 엘리먼트를 렌더링합니다.

👎잘못된 사례
React는 DOM 엘리먼트를 렌더합니다.

👍모범 사례
함수를 바인딩해야 합니다.
```

## 당신과 여러분은 없어도 됩니다.

아주 가끔 꼭 필요할 때가 있기는 하지만 영어 표현에 많은 `당신`이나 `여러분`, `우리`같은 표현은 안 쓰는 게 훨씬 자연스럽습니다.

```
🇬🇧 Let's say you want to output "Hello, world" in an DOM element.

👍모범 사례
DOM 엘리먼트에 "Hello, World"를 표현한다고 생각해봅시다.

👎잘못된 사례
당신이 DOM 엘리먼트에 "Hello, World"를 표현하고 싶다고 생각해봅시다.
```

## 피동형 문장에 주의하세요.

사실 원칙대로라면 `~되다`같은 수동태도 가능하면 억제하는 편이 좋지만 실제로 작업을 하다 보면 써야 문장이 자연스러울 때도 있습니다. 다만 `보여지다`, `생각되다`와 같은 불필요한 피동형 문장은 자제하는 편이 좋습니다.

```
🇬🇧 Elements appeared on the screen

👍모범 사례
화면에 보이는 엘리먼트

👎잘못된 사례
화면에 보여지는 엘리먼트
```

## 똑같은 표현은 비슷한 표현으로 대체하면 문장이 더 유려해집니다.

번역문에서 흔히 나타나는 문제가 영어 단어를 1:1로 번역하다 보니 표현이 단조로워진다는 점입니다. 예를 들어 `common`은 `일반적으로`라고만 번역한다거나 `call`은 `호출한다`라고만 번역하는 사례가 많습니다. 가까운 위치에서 똑같은 표현이 여러 차례 등장할 때 조금씩 표현을 바꾸어주면 문장이 더 읽기 좋아집니다. `common`이나 `commonly`는 `일반적으로`, `널리`, `흔히` 등으로 바꿀 수 있고 `call`, `invoke` 등은 `호출하다`, `실행하다` 등으로 바꿀 수 있습니다.

```
👍모범 사례
이때 흔히 사용되는 패턴은 일반 자바스크립트 객체를 전달하는 것이다.

👎잘못된 사례
이때 일반적으로 사용되는 패턴은 일반 자바스크립트 객체를 전달하는 것이다. 
```

## 어색하지 않다면 단수형을 사용합시다.

원래 우리말에서는 `~들`이라는 복수형 표현을 그리 널리 사용하지 않습니다. 물론 문장의 의미에 따라 반드시 복수의 객체임을 명시해야 할 때가 있긴 하지만, 그 외의 경우라면 단수형으로 표현하는 편이 대체로 자연스럽습니다.

```
🇬🇧 The examples below demonstrate the differences.

👍모범 사례
아래 예시는 위에서 언급한 차이점을 보여줍니다.

👍모범 사례 - 복수형 표현이 필요한 경우
아래 예시는 위에서 언급한 여러 차이점을 보여줍니다.

👎잘못된 사례
아래 예시들은 위에서 언급한 차이점들을 보여줍니다.
```

## If는 생략할 수도 있습니다.

`If`로 시작하는 문장의 번역이 항상 `만약`으로 시작할 필요는 없습니다. 틀린 번역은 아니지만 한국어에서는 `~한다면`이라는 어미가 이미 조건 또는 상황의 가정을 의미하므로 때로는 `만약`이 없어도 충분히 말이 됩니다. 아래 예시는 인접한 두 문장이 모두 `만약`으로 시작하고 있었습니다. 한 문장 만이라도 `만약`을 생략하면 조금 더 읽기 수월해집니다.

```
🇬🇧If you load React from a `<script>` tag, .... If you use ES6 with npm, ...

👍모범 사례
React를 <script> 태그로 불러온다면 ... ES6와 npm을 함께 사용한다면 ...

👎잘못된 사례
만약 React를 <script> 태그로 불러온다면 ... 만약 ES6와 npm을 함께 사용한다면 ...
```

**Comment by Ailrun** [comment]
피동형 문장과 관련된 예시에 '보때다' 라는 잘못된 단어가 등장하는데, '보이다' 의 오타로 보입니다.
```
🇬🇧 Elements appeared on the screen

👍모범 사례
화면에 보이는 엘리먼트

👎잘못된 사례
화면에 보여지는 엘리먼트
```
를 의도하신 게 맞나요?

**Comment by taggon** [comment]
@Ailrun 어라... 그게 왜 그렇게 저장됐을까요... ;; 에디터에서 써서 옮긴 글인데 에디터에는 보이다로 되어있는데요. 이상하네요. 수정하겠습니다 ㅎㅎ

**Comment by Ailrun** [comment]
덧붙여보자면

## 강조가 필요한 경우에는 이탤릭체를 영문에 적용합시다.
한글에는 이탤릭체에 해당하는 기울임꼴이 존재하지 않습니다. 컴퓨터 상에서 볼 수 있는 한글 이탤릭체들은 한글 글씨를 기울여서 만든 것으로, 영문의 경우 이탤릭체를 따로 글씨체에 포함하는 것과는 다른 방식으로 만드는 경우가 많습니다. 따라서 이탤릭체를 사용해야할 경우에는 다음과 같이 영문에 적용하도록 합니다.

> 🇬🇧 This _inversion of control_ can make your code cleaner in many cases by reducing the amount of props you need to pass through your application and giving more control to the root components.
>
> 👍모범 사례
> 이런 제어의 역전( _inversion of control_ )을 사용하면 어플리케이션 내에서 필요한 Props 의 갯수를 줄일 뿐만 아니라 최상위 컴포넌트에게 더 많은 자유를 줄 수 있고, 결과적으로 코드를 더 깔끔하게 만들 수 있습니다.
> 👎잘못된 사례
> 이런 _제어의 역전_ 을 사용하면 어플리케이션 내에서 필요한 Props 의 갯수를 줄일 뿐만 아니라 최상위 컴포넌트에게 더 많은 자유를 줄 수 있고, 결과적으로 코드를 더 깔끔하게 만들 수 있습니다.

는 어떤가요?

**Comment by Ailrun** [comment]
또한 쉼표의 경우에는 예시로 드신
```
JavaScript와 마찬가지로, 가독성이 좋아 보이는 방식을 선택하면 됩니다.
```
가 한글 맞춤법 링크의 12 번 경우에 해당하기 때문에 ('JavaScript와 마찬가지로'가 'JavaScript 와 마찬가지로 가독성이 좋은'과 같이 연결되는 것이 아니라, 'JavaScript 와 마찬가지로 방식을 선택' 하는 것으로 연결되기 때문에) 부적절하다고 생각합니다.

제 생각에는 국어 내에서도 쉼표를 사용해야할 곳이 많기 때문에, 쉼표를 제한적으로 사용한다기보다는 '쉼표를 무조건 쉼표로 번역하지 맙시다' 정도의 권고가 어떨까 싶네요.

**Comment by hg-pyun** [comment]
At this point, it looks good to organize it and manage it by making it into an md file.
> 이쯤에서 정리한후 md파일로 만들어서 관리하는 것이 좋아 보입니다.

**Comment by taggon** [comment]
@Ailrun 
쉼표 부분에 관해서는 주신 의견을 반영했습니다. 예문이 적절하지 않았던 것 같아서 예문도 수정했고요.

이탤릭체의 사용에 대해서는 확신이 없어서 아직 반영하지 않았습니다. 서적 번역에서는 기울임꼴 대신 아예 다른 모양의 글꼴을 사용하거나 굵은 글씨로 표현하곤 하는데 온라인 문서에서는 어떤 게 더 좋을지 모르겠습니다. 이 부분은 다른 분들의 의견을 기다려보겠습니다.

**Comment by Ailrun** [comment]
굵은 글씨로 표기하지 않은 것은 문서에서 굵은 글씨가 다른 방식(용어의 표시가 아닌 단순 강조)로 사용되고 있어서였습니다.
다른 글씨체로 표기하는 것은 MD 에서 간단하지가 않은지라... 약간 HTML 입히면 되기는 하겠습니다만....

**Comment by taehwanno** [comment]
textlint linter를 사용해서 일정 부분 자동화할 수 있을 것 같아요.
#42 에서 쌍점, 쌍반점과 외래어 표기, 약속된 용어에 대한 규칙(rule)을 만들어서 master에 반영해놨습니다.

**Comment by taggon** [comment]
별다른 의견 없으시면 일단 현재까지 작성된 내용을 기준으로 위키 문서를 작성하고 다시 추가해가는 게 어떨까 합니다.
cc @reactjs/reactjs-org-korean-translation

**Comment by taehwanno** [comment]
@taggon 좋아요 :) :rocket:

**Comment by simsim0709** [comment]
@taggon 네 저도 좋습니다.

**Comment by gnujoow** [comment]
@taggon 좋습니다. pr template에도 추가하도록 할게요
cc @reactjs/reactjs-org-korean-translation

**Comment by taggon** [comment]
https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation
위키 페이지를 만들었습니다. 추가할만한 항목이 있으면 따로 이슈를 만들어 진행하면 좋을 것 같습니다.

위키 페이지를 만들었으므로 이슈 닫겠습니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 자바스크립트 튜토리얼 한글화 프로젝트에서 메인테이너로 활동하고있는 이보라입니다. 리액트 공식문서의 위키를 참고하여 저희 프로젝트의 위키를 작성하게되어, 알려드리고자 이렇게 코멘트를 답니다. KIGO번역스타일 가이드를 참고하여 몇가지 사항을 더 추가하였고, 약간의 수정도 해보았습니다.

링크: https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80

혹시라도 불편하시다면 직접링크거는것으로 대체하겠습니다. 감사합니다.

**Comment by de24world** [comment]
모범 사례에서 일부만 영어 원문만 표기가 되어있는데, 모두 영어 원문이 표기되어있으면 좋을거 같습니다.
