### ISSUE TITLE
Using communication tool for translation team

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.reactjs.org#3]
How about using some communication tools like slack? I wish there was a channel to exchange opinion. Say your ideas! 

Thank you.

**Comment by seungha-kim** [comment]
There is React Korea Slack workspace -> http://bit.ly/2Fvzis1

**Comment by taehwanno** [comment]
I agree to create a new channel on React Korea Slack.

**Comment by ENvironmentSet** [comment]
yes, we need one. #public channel is used by common users, we'd better not to disturb them.

**Comment by taggon** [comment]
Good idea. I just created _#translation_ public channel in [React Korea Slack](http://bit.ly/2Fvzis1) workspace. Please join in if you're interested in the translation.

**Comment by taehwanno** [comment]
@b9words Can you tell if you're on the channel? If you don't, please join us :)

**Comment by taggon** [comment]
This issue is already resolved as I created the #translation channel. Can we close this?

**Comment by taehwanno** [comment]
I think it's okay. I specified an invitation link in the #1 description.

**Comment by gnujoow** [comment]
as link is included #1, i will close this issue
