### ISSUE TITLE
Translating the new official document

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.reactjs.org#373]
React의 새로운 공식문서 번역이 시작되는 것 같습니다. 아래 스레드에서 논의가 진행되는 것 같은데 트래킹하면 좋을 것 같습니다.
A new official document translation of React seems to begin. The discussion seems to be taking place in the thread below, so it would be nice to track it.

https://github.com/reactjs/reactjs.org/issues/4135#issue-1066313243

**Comment by taehwanno** [comment]
좋습니다 진행해보시져

**Comment by taehwanno** [comment]
React Korea의 Facebook 그룹과 Slack의 translation 채널에 공유했습니다

**Comment by hg-pyun** [comment]
생활코딩과 프론트엔드 개발그룹에 공유해보겠습니다.

**Comment by taehwanno** [comment]
#374 에서 진행상황 관리하므로 해당 이슈는 닫도록 할게요~!
