### ISSUE TITLE
[Beta] Translate custom tag component

### ISSUE THREAD

**Issue by alstn2468** [reactjs/ko.reactjs.org#378]
`YouWillLearn`, `Gotcha`, `Recap`, `Challenges` 와 같은 커스텀 태그 컴포넌트에 있는 영문 값들도 수정해주는 게 좋을 것 같다는 생각이 있습니다.
제가 번역을 진행한 Javascript in jsx with curly braces 에서 확인할 수 있는 컴포넌트는 이정도 있었습니다.

- `Challenges`

<img src='https://user-images.githubusercontent.com/30997311/145038346-2fd7af2b-2f5f-408b-8e5e-3928d87f7dbe.png' width='600' />

- `ToC`

<img src='https://user-images.githubusercontent.com/30997311/145038422-00262f02-6991-487a-b4e2-9043c00cd61e.png' width='200' />

- `ExpandableCallout`

<img src='https://user-images.githubusercontent.com/30997311/145038470-f0f93668-74e9-47f3-8635-58908f5f40d2.png' height='100' />

- `MDXComponent/YouWillLearn`

<img src='https://user-images.githubusercontent.com/30997311/145038556-f50ec477-e753-4823-8294-5227cbeeb609.png' height='200' />

**Comment by taehwanno** [comment]
좋습니다. 지금 번역 진행 중이신 페이지와는 분리해서 번역해보시져 ㅎㅎ
