### ISSUE TITLE
eslint error (no-unused-vars)

### ISSUE THREAD

**Issue by de24world** [reactjs/ko.reactjs.org#379]
https://github.com/reactjs/ko.reactjs.org/blob/4daa062467bb3469883c87dd8daf46db771a30eb/plugins/gatsby-transformer-home-example-code/gatsby-node.js#L6

**Comment by taehwanno** [comment]
업스트림 저장소 살펴보니 최근에 https://github.com/reactjs/reactjs.org/pull/4115 에서 제거됐네요. #369 처럼 주기적으로 업스트림의 변화를 봇이 만들어주고 있어서 그때 해결되지 않을까 싶습니다 ㅎㅎ

**Comment by hg-pyun** [comment]
오 그럼 날먹을 기다려 봅니다.

**Comment by hg-pyun** [comment]
오 그럼 기다려 봅니다.

**Comment by taehwanno** [comment]
Fixed by #392
