### ISSUE TITLE
Prior works

### ISSUE THREAD

**Issue by taehwanno** [reactjs/ko.reactjs.org#4]
There are some Korean translations of official React documents. I think we can translate them a little bit faster if we can use the previously translated text. So, I list the translation posts that are accessible by URL but are not committed in the current repository. The translation lists are listed in the latest order of publication date. The pages that did not find translations are not listed below.

If you would like to recommend another translation, please let me know by comment. I will update the description of this issue.

:warning: Please note that this does not mean that you "must use" the following listed translations. The translations can also be protected by copyright, so if you want to refer to them, it's a good way to work with permission in advance. Please respect the translator who worked in advance.

## Core Pages :book:

- Home Page
    - https://reactjs-org-ko.netlify.com/
    - https://reactjs-kr.firebaseapp.com/
- Tutorial
    - https://reactjs-org-ko.netlify.com/tutorial/tutorial.html
    - https://reactjs-kr.firebaseapp.com/tutorial/tutorial.html

### Basics

- Hello World
    - https://www.gaesignerblog.com/post/13
    - https://reactjs-kr.firebaseapp.com/docs/hello-world.html
- Introducing JSX
    - https://www.gaesignerblog.com/post/14
    - https://reactjs-kr.firebaseapp.com/docs/introducing-jsx.html
- Rendering Elements
    - https://www.gaesignerblog.com/post/17
    - https://reactjs-org-ko.netlify.com/docs/rendering-elements.html
    - https://reactjs-kr.firebaseapp.com/docs/rendering-elements.html
- Components and Props
    - https://www.gaesignerblog.com/post/18
    - https://reactjs-org-ko.netlify.com/docs/components-and-props.html
    - https://reactjs-kr.firebaseapp.com/docs/components-and-props.html
- State and Lifecycle
    - https://www.gaesignerblog.com/post/24
    - https://reactjs-kr.firebaseapp.com/docs/state-and-lifecycle.html
- Handling Events
    - https://www.gaesignerblog.com/post/26
    - https://reactjs-org-ko.netlify.com/docs/handling-events.html
    - https://reactjs-kr.firebaseapp.com/docs/handling-events.html
- Conditional Rendering
    - https://www.gaesignerblog.com/post/27
    - https://reactjs-org-ko.netlify.com/docs/conditional-rendering.html
    - https://reactjs-kr.firebaseapp.com/docs/conditional-rendering.html
- Lists and Keys
    - https://www.gaesignerblog.com/post/28
    - https://reactjs-org-ko.netlify.com/docs/lists-and-keys.html
    - https://reactjs-kr.firebaseapp.com/docs/lists-and-keys.html
- Forms
    - https://www.gaesignerblog.com/post/29
    - https://reactjs-org-ko.netlify.com/docs/forms.html
    - https://reactjs-kr.firebaseapp.com/docs/forms.html
- Lifting State Up
    - https://www.gaesignerblog.com/post/30
    - https://reactjs-org-ko.netlify.com/docs/lifting-state-up.html
    - https://reactjs-kr.firebaseapp.com/docs/lifting-state-up.html
- Composition vs Inheritance
    - https://www.gaesignerblog.com/post/33
    - https://reactjs-org-ko.netlify.com/docs/composition-vs-inheritance.html
    - https://reactjs-kr.firebaseapp.com/docs/composition-vs-inheritance.html
- Thinking in React
    - https://www.gaesignerblog.com/post/34
    - https://reactjs-org-ko.netlify.com/docs/thinking-in-react.html
    - https://reactjs-kr.firebaseapp.com/docs/thinking-in-react.html

### API Reference

- React
- React.Component
    - https://reactjs-org-ko.netlify.com/docs/react-component.html
- ReactDOM
- ReactDOMServer
    - https://www.gaesignerblog.com/post/63
- DOM Elements
- SyntheticEvent
- Test Utilities
- Shallow Renderer
- Test Renderer
- JS Environment Requirements
- Glossary
    - Check out [#2](https://github.com/reactjs/ko.reactjs.org/issues/2)

### Navigation

- tutorial/nav.yml
    - https://reactjs-kr.firebaseapp.com/tutorial/tutorial.html
- docs/nav.yml
    - https://reactjs-org-ko.netlify.com/docs/hello-world.html
    - https://reactjs-kr.firebaseapp.com/docs/hello-world.html

### Installation

- Getting Started
    - https://reactjs-kr.firebaseapp.com/docs/installation.html#react-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0
- Add React to a Website
- Create a New React App
    - https://reactjs-kr.firebaseapp.com/docs/installation.html#creating-a-new-application
- CDN Links
    - https://reactjs-kr.firebaseapp.com/docs/installation.html#cdn-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

### Hooks

- Introducing Hooks
- Hooks at a Glance
    - https://chatoo2412.github.io/javascript/react/react-hooks-overview/
- Using the State Hook
- Using the Effect Hook
- Rules of Hooks
- Building Your Own Hooks
- Hooks API Reference
- Hooks FAQ

### Advanced Guides

- Accessibility
    - https://www.gaesignerblog.com/post/47
- Code-Splitting
    - https://www.gaesignerblog.com/post/51
- Context
    - http://www.gaesignerblog.com/post/55
    - https://reactjs-org-ko.netlify.com/docs/context.html
    - https://reactjs-kr.firebaseapp.com/docs/context.html
- Error Boundaries
    - https://www.gaesignerblog.com/post/57
    - https://reactjs-kr.firebaseapp.com/docs/error-boundaries.html
- Forwarding Refs
    - https://www.gaesignerblog.com/post/60
- Fragments
    - https://www.gaesignerblog.com/post/70
    - https://reactjs-kr.firebaseapp.com/docs/fragments.html
- Higher-Order Components
    - https://reactjs-org-ko.netlify.com/docs/higher-order-components.html
    - https://reactjs-kr.firebaseapp.com/docs/higher-order-components.html
- Integrating with Other Libraries
    - https://www.gaesignerblog.com/post/72
- JSX In Depth
    - https://reactjs-org-ko.netlify.com/docs/jsx-in-depth.html
    - https://reactjs-kr.firebaseapp.com/docs/jsx-in-depth.html
- Optimizing Performance
    - https://reactjs-org-ko.netlify.com/docs/optimizing-performance.html
    - https://reactjs-kr.firebaseapp.com/docs/optimizing-performance.html
- Portals
    - https://www.gaesignerblog.com/post/76
    - https://reactjs-kr.firebaseapp.com/docs/portals.html
- React Without ES6
    - https://reactjs-kr.firebaseapp.com/docs/react-without-es6.html
- React Without JSX
   - https://reactjs-kr.firebaseapp.com/docs/react-without-jsx.html
- Reconciliation
    - https://reactjs-org-ko.netlify.com/docs/reconciliation.html
    - https://reactjs-kr.firebaseapp.com/docs/reconciliation.html
- Refs and the DOM
    - https://reactjs-org-ko.netlify.com/docs/refs-and-the-dom.html
    - https://reactjs-kr.firebaseapp.com/docs/refs-and-the-dom.html
-  Render Props
    - https://medium.com/@la.place/react-render-props-pattern-1c53a6b9645c
- Static Type Checking
    - https://reactjs-kr.firebaseapp.com/docs/static-type-checking.html
- Strict Mode
- Typechecking With PropTypes
    - https://reactjs-kr.firebaseapp.com/docs/typechecking-with-proptypes.html
- Uncontrolled Components
    - https://reactjs-org-ko.netlify.com/docs/uncontrolled-components.html
    - https://reactjs-kr.firebaseapp.com/docs/uncontrolled-components.html
- Web Components

## Additional Information

- [https://reactjs-kr.firebaseapp.com/*](https://reactjs-kr.firebaseapp.com/)
    - All links have been translated based on React version v16.2.0.
    - Those have not been maintained since January 22, 2018.
    - See [comparing changes](https://github.com/reactjs/reactjs.org/compare/master...techhtml:ko-kr) with reactjs/reactjs.org
- [reactkr/discuss #4](https://github.com/reactkr/discuss/issues/4)
    - This is a translation related thread that was attempted by the React community in Korea.
    - But it does not seem to be maintained based on [this issue](https://github.com/reactkr/discuss/issues/8) after React v0.14.0-alpha.
    - You can see related branches.
      - https://github.com/reactkr/react/tree/reactkr
      - https://github.com/reactkr/react/tree/translation-v15
      - https://github.com/reactkr/react/tree/translation
- [https://reactjs-org-ko.netlify.com/*](https://reactjs-org-ko.netlify.com)
    - [This repository (branch: `ko-kr-180116`)](https://github.com/seungha-kim/reactjs.org/tree/ko-kr-180116) is fork of https://reactjs-kr.firebaseapp.com/
    - Some fixes are included.
    - See [comparing changes](https://github.com/techhtml/reactjs.org/compare/ko-kr...seungha-kim:ko-kr-180116) with upstream repository.

**Comment by gnujoow** [comment]
thank this would be very helpful!

**Comment by hg-pyun** [comment]
LGTM

**Comment by ENvironmentSet** [comment]
quality of those translations looks great. :))

**Comment by seungha-kim** [comment]
[This repository](https://github.com/seungha-kim/reactjs.org/tree/ko-kr-180116) is my fork of https://reactjs-kr.firebaseapp.com

The website is [here](https://reactjs-org-ko.netlify.com/)

**Comment by taehwanno** [comment]
@seungha-kim Based on [comparing changes](https://github.com/techhtml/reactjs.org/compare/ko-kr...seungha-kim:ko-kr-180116), I updated the issue description.
Please let me know if I missed some docs.

**Comment by chatoo2412** [comment]
I have one: https://chatoo2412.github.io/javascript/react/react-hooks-overview/

**Comment by taehwanno** [comment]
@chatoo2412 Thanks. The description was updated.

**Comment by taehwanno** [comment]
Updated: I deleted each translation status because I think it was not meaningful.

**Comment by taehwanno** [comment]
Because many pages have been translated, I will close this.
