### ISSUE TITLE
Conflict Merge 

### ISSUE THREAD

**Issue by circlezero** [reactjs/ko.reactjs.org#418]
<img width="408" alt="스크린샷 2022-02-09 오후 10 47 15" src="https://user-images.githubusercontent.com/16660871/153213940-ede96491-9430-4e88-8a7b-670beff5f90c.png">

우연찮게 발견하게 되었는데
Conflict가 된 상태 그대로 Merge가 되면서 문제가 생긴거 같습니다.

**Comment by hmu332233** [comment]
이슈가 이미 있어서 링크와 이미지 남깁니다. 😮 

[Route-based code splitting](https://ko.reactjs.org/docs/code-splitting.html#route-based-code-splitting)

![image](https://user-images.githubusercontent.com/10302969/153589579-0d97910b-7e26-46fc-9802-2f48969aff07.png)

**Comment by zwonlala** [comment]
https://ko.reactjs.org/docs/jsx-in-depth.html
위 문서에서도 발생해서 찾아보니 이미 등록된 이슈군요!

**Comment by artvelop** [comment]
https://github.com/reactjs/ko.reactjs.org/pull/446

안그래도 jsx문서 읽다가 발견해서 PR등록했습니다

**Comment by hg-pyun** [comment]
이건 따로 챙겨보겠습니다.
