### ISSUE TITLE
소스코드 예제 typo

### ISSUE THREAD

**Issue by ynifamily3** [reactjs/ko.reactjs.org#481]
https://github.com/reactjs/ko.reactjs.org/blob/f265301642079f05066231c005e73672eb2f0f91/content/docs/concurrent-mode-patterns.md

AS-IS
`const [startTransition, isPending] = useTransition({`

TO-BE
`const [isPending, startTransition] = useTransition({`

* 혹시, 아카이브된 문서라 업데이트가 이루어지지 않고 있나요?

**Comment by gnujoow** [comment]
https://github.com/reactjs/reactjs.org/issues/4135#issuecomment-981865846
https://github.com/reactjs/ko.reactjs.org/issues/374
에 따라 새로운 버전의 문서를 번역하고 있습니다. 해당 문서에 대한 typo라면 PR을 올려주시면 감사하곘습니다.
