### ISSUE TITLE
오번역 수정 요청

### ISSUE THREAD

**Issue by ssohymind** [reactjs/ko.reactjs.org#487]
https://reactjs.org/docs/reconciliation.html#recursing-on-children

**React will mutate every child instead of realizing it can keep the `<li>Duke</li>` and `<li>Villanova</li>` subtrees intact. This inefficiency can be a problem.**

AS-IS:
React는 모든 자식을 변형시켜 `<li>Duke</li>` 및 `<li>Villanova</li>` 서브 트리를 그대로 유지할 수 있음을 깨닫지 못합니다. 이러한 비효율은 문제가 될 수 있습니다.

TO-BE:
React는 `<li>Duke</li>` 및 `<li>Villanova</li>` 서브 트리를 그대로 유지할 수 있음을 알아차리는 것 대신에 모든 자식을 변형시킬 것입니다. 이러한 비효율은 문제가 될 수 있습니다.

**Comment by gnujoow** [comment]
해당 부분에 대한 Pull Request를 올려주시면 감사하겠습니다.
