### ISSUE TITLE
Using Github Issues as unit of translation.

### ISSUE THREAD

**Issue by ENvironmentSet** [reactjs/ko.reactjs.org#5]
As we know, this project have **many volunteers**, and **documents**.

So, I think we need a **board** to share each work's status, blocking problems, etc.. also to prevent duplication of translation, and to work more effectively.

and, **github issues** and **projects** will do us.
could you share your idea about this?

**Comment by tesseralis** [comment]
If you think a board would help you keep track, you're welcome to do so! Japanese and French have been able to get by using a single issue like https://github.com/reactjs/ko.reactjs.org/issues/1, but if it makes sense to your team then go for it!

**Comment by hg-pyun** [comment]
I think #1 would be enough, but do you have any other ideas?

**Comment by ENvironmentSet** [comment]
okay, I will follow you :))
