### ISSUE TITLE
Fixing Outdated Repository

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.reactjs.org#555]
현재 한국문서 저장소가 outdated 되어있는 상태라 이걸 해결하고 싶습니다. 

1. 어떤 작업을 해야할지 리스트를 작성
2. 베타 공식문서 번역에 관한 운영 방침 정의

Co-Worker: @MaxKim-J, @eomttt, @goofcode

**Comment by hg-pyun** [comment]
+ 저장소 내에서 한국어와 영어가 혼용되어 사용되고 있는데, 이걸 허용할지 말지도 정하면 좋을 것 같군요.

**Comment by hg-pyun** [comment]
작업 TODO 리스트
- 가장 최신의 repository sync @hg-pyun @MaxKim-J, @eomttt, @goofcode
- PR 정리하기 @hg-pyun 
- 소통 채널 마련하기 (기존 Slack을 계속 사용할지?)
- 기존 beta 번역을 어떻게 할지 의논하기
- Wiki 고도화

**Comment by hg-pyun** [comment]
@tesseralis @gaearon 

I'm going to do maintenance work with them, so could you add them to the organization?
-> @MaxKim-J, @eomttt, @goofcode

**Comment by hg-pyun** [comment]
기존 PR 정리하고 안내하기 -> @MaxKim-J

**Comment by hg-pyun** [comment]
기존 번역문서 안내 -> @hg-pyun

**Comment by hg-pyun** [comment]
온보딩 문서 만들기 -> @eomttt

**Comment by hg-pyun** [comment]
커뮤니티는 기존 슬랙 활용하는 것으로 논의 -> https://react-korea.slack.com/archives/CG20A87A9

**Comment by taehwanno** [comment]
한동안 메인테이닝에 참여하지 못했네요 ㅜㅜ 참고로 React Korea 슬랙 채널이 슬랙의 무료 요금제 정책 변화로 인해 디스코드로 옮기게 됐습니다. 디스코드의 [#번역 소모임](https://discord.gg/YXdTyCh5KF)이 따로 있으니 여기서 대화하시는게 좋아보여요! 링크는 초대 링크입니다. #번역 소모임의 관리자 권한은 제가 가지고 있는데 혹시 필요하시면 말씀해주세요.

**Comment by hg-pyun** [comment]
@taehwanno 오 디코가 있는줄 몰랐군요. 해당 채널에서 논의를 이어가 보도록 하겠습니다. 🙇‍♂️

**Comment by SyingSHY** [comment]
> 2번에 추가로 논의하고 싶은 것은, 저장소 내에서 한국어와 영어가 혼용되어 사용되고 있는데, 이걸 허용할지 말지도 정하면 좋을 것 같군요.

안녕하세요! 현 Docs 번역에 참여하면서 느낀 점 말씀드려 봅니다.

현재 번역 과정에서 참고하도록 제시된 [Translate Glossary](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary) 위키 항목의 마지막 업데이트로부터 많은 시간이 지났고 React도 많은 버전 업을 거쳤습니다.
위키 생성 시점에 존재했던 대부분의 React 개념 및 기능들에 대해서는 해당 항목에서 지시한 내용에 따라 번역이 잘 이루어져 왔다고 보여집니다.
다만 이후 새로 추가된 개념 및 기능들(Suspense, Hydration 등)의 경우에는 그에 맞춰 대응될 번역 합의가 정해져 있지 않아 원문을 그대로 가져오거나, 병기하는 경우가 잦았던 것으로 생각됩니다.

앞으로 번역이 다시 활성화되어 소통과 피드백이 원활해진다면 문제 없겠으나, 그렇지 못할 경우를 대비하여

> 생명주기(Lifecycle) / Lifecycle(생명주기) / Lifecycle(생명주기, 임시표기)

와 같은 형태로 #2 에서 번역 합의가 도출되기 전인 단어들의 통일된 임시 표기법을 정해 놓으면 이후 번역 속도 및 유지 관리 측면에서 좋을 것 같습니다.

**Comment by hg-pyun** [comment]
@SyingSHY 좋은 생각인 것 같습니다. 이 안건은 새 이슈로 등록해서 논의를 이어나가면 좋을 것 같군요.

**Comment by eomttt** [comment]
@hg-pyun 요것은 제가 챙겨보도록 하겠습니다 
cc @SyingSHY

**Comment by gnujoow** [comment]
> @tesseralis @gaearon
> 
> I'm going to do maintenance work with them, so could you add them to the organization? -> @MaxKim-J, @eomttt, @goofcode

https://github.com/orgs/reactjs/teams/reactjs-org-korean-translation 여기에 추가하려고 했는데 organization추가가 먼저 되어야하는것 같습니다. 제가 한번 요청해볼게요

**Comment by gnujoow** [comment]
https://github.com/reactjs/reactjs.org-translation#adding-a-maintainer 의 가이드에 따라서 새로운 메인테이너를 추가했습니다.

**Comment by hg-pyun** [comment]
@gnujoow 가이드라인이 따로 있었군요. 감사합니다 🙇‍♂️

**Comment by gnujoow** [comment]
> @gnujoow 가이드라인이 따로 있었군요. 감사합니다 🙇‍♂️

지난 maintainer관련된 PR들이 리뷰되지 않고 꽤 오랬동안 방치되었더라구요, 해서 제가 직접 merge를 했습니다. 
https://github.com/reactjs/reactjs.org-translation/pull/218

지금은 당장 maintainer 변경이 없는것 같은데, 내일 다시 한번 확인해보겠습니다.
@hg-pyun 

운영 방침에대해서는 지금 이슈에서 이야기하고, 각각 세부적인 논의는 아래에서 해보면 어떨까요?
https://github.com/orgs/reactjs/teams/reactjs-org-korean-translation

**Comment by hg-pyun** [comment]
@gnujoow 님 안녕하세요! 현재 베타 공식문서가 릴리즈 되면서 기존 레포지토리가 레거시로 전환되는 바람에 방향성에 대한 논의가 아래 스레드에서 진행되고 있습니다. 이게 어느정도 정리된 후에 액션을 할 수 있지 않을까 하는 의견입니다.

https://github.com/reactjs/react.dev/issues/4135#issuecomment-1479242203

**Comment by hg-pyun** [comment]
관련해서 주말에 한판 정리해서 이슈로 등록해 보도록 하겠습니다 🙇

**Comment by hg-pyun** [comment]
이후 논의는 #581 에서 이어서 진행하도록 하겠습니다. 🙇‍♂️
