### ISSUE TITLE
Translate READEME.md

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.reactjs.org#91]
It's not necessary, but Is it okay translate `README.md` as well?

**Comment by taehwanno** [comment]
Yepp :)

- https://github.com/reactjs/ru.reactjs.org
- https://github.com/reactjs/uk.reactjs.org

**Comment by hg-pyun** [comment]
@taehwanno Thank you :), Could I get the page?

**Comment by taehwanno** [comment]
Sure!
