### ISSUE TITLE
PR request with no-response

### ISSUE THREAD

**Issue by gnujoow** [reactjs/ko.reactjs.org#94]
there are some PR requests with a month long no response from PR author.

For effective project progress and participation of other participants, I suggest to make rule dealing with un-managed reviewed pull requests.

@reactjs/reactjs-org-korean-translation

**Comment by hg-pyun** [comment]
If we don't get an answer, how do you transfer it to someone else?

**Comment by taehwanno** [comment]
It's time to decide how to assign other people about no response pull request for a long time.

if we assign them to other translators, the translator that is not a maintainer needs to fork the pull request author's repository and submits a new pull request.
(e.g. need to fork `taehwanno/ko.reactjs.org`. not a `reactjs/ko.reactjs.org`)

I think it's better to maintain review threads in the already submitted pull request. So, how about one of the maintainers do the translation on behalf of pull request author with no response pull request over 3~4 weeks? the period can be changed.

**Comment by simsim0709** [comment]
I agree with @taehwanno. We may have another label for that something like `no-response`. Then, we can continue on the unfinished translation.

**Comment by taehwanno** [comment]
I will first try this decision starting at #18

**Comment by simsim0709** [comment]
I'll try #76

**Comment by simsim0709** [comment]
#76 is done.

I'll try #46

**Comment by taehwanno** [comment]
I added `no long-term response` label for no response pull request over 2 weeks.

**Comment by simsim0709** [comment]
#46 done.

I'll try #47

**Comment by taehwanno** [comment]
I will try #109

**Comment by gnujoow** [comment]
following items are newly added.
- [ ] #121
- [ ] #123

**Comment by taehwanno** [comment]
I will try #121

**Comment by taehwanno** [comment]
Because many pages have been already translated, I will close this.
